proxies:
proxy-groups:
  - name: TOUKA
    type: select
    proxies: [LYCORIS]
    use: [CLASH]
  - name: LYCORIS
    type: url-test
    filter: 'Fiber|Contabo|HostSG|Hurricane Electric'
    url: http://cp.cloudflare.com/generate_204
    ninterval: 300
    use: [CLASH]
proxy-providers:
  CLASH:
    type: file
    path: ./confs/clash.yaml
    url: ""
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 1200
rules:
  - IP-CIDR,127.0.0.1/32,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - MATCH,TOUKA