proxies:
  - name: sggs ss
    type: ss
    server: sggs-sock.tcpvpn.com
    port: 443
    cipher: aes-256-gcm
    password: "shadowsocksipSG^&!@YT"
    plugin: obfs
    plugin-opts:
      mode: tls
      host: kh.google.com
proxy-groups:
  - {name: "LYCORIS", type: select, proxies: [sggs ss], use: [CLASH]}
proxy-providers:
  CLASH:
    type: file
    path: ./confs/clash.yaml
    url: ""
    health-check:
      enable: true
      url: 'http://cp.cloudflare.com/generate_204'
      interval: 1200
rules:
  - IP-CIDR,127.0.0.1/8,DIRECT,no-resolve
  - MATCH,LYCORIS